// Writes supabase/seed.sql from the fictional demo listings in lib/data.ts.
// Run: node scripts/generate-seed.ts
import { writeFileSync } from 'node:fs'
import { seed } from '../lib/data.ts'

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  if (Array.isArray(v)) return 'array[' + v.map(q).join(', ') + ']::text[]'
  return "'" + String(v).replace(/'/g, "''") + "'"
}

const S = seed()
const cols = ['id', 'type', 'biz', 'mat', 'loc', 'from_date', 'to_date', 'arch', 'cond', 'qty', 'price', 'disp', 'chem', 'uses', 'done', 'res', 'move_r', 'use1', 'min_qty', 'max_qty', 'max_km', 'max_price', 'alt']
const rows = S.L.map(l => {
  const base = [l.id, l.type, l.biz, l.mat, l.loc, l.from, l.to, !!l.arch]
  const rest = l.type == 'Supply'
    ? [l.cond, l.qty, l.price, l.disp, l.chem, l.use, l.done, l.res, !!l.moveR, null, null, null, null, null, null]
    : [null, null, null, null, null, null, 0, 0, false, l.use1, l.min, l.max, l.maxKm, l.maxPrice, l.alt]
  return '  (' + [...base, ...rest].map(q).join(', ') + ')'
})

const tx = S.T.map(t =>
  `  (${q(t.id)}, ${q(t.s)}, ${q(t.d)}, ${t.q}, ${t.price}, ${t.step}, ${q(JSON.stringify(t.log))}::jsonb)`)

const sql = `-- Generated by scripts/generate-seed.ts. Fictional businesses (owner_id is null).
insert into public.listings (${cols.join(', ')}) values
${rows.join(',\n')}
on conflict (id) do nothing;

insert into public.transactions (id, supply_id, demand_id, q, price, step, log) values
${tx.join(',\n')}
on conflict (id) do nothing;
`

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql)
console.log(`Wrote ${S.L.length} listings and ${S.T.length} transaction(s) to supabase/seed.sql`)
